dir = usr/share/themes

files = \
	Clearlooks/gtk-2.0/gtkrc \
    dark/gtk-2.0/assets/arrow-down-insens.png  \
    dark/gtk-2.0/assets/arrow-down-prelight.png  \
	dark/gtk-2.0/assets/arrow-down-small-insens.png  \
	dark/gtk-2.0/assets/arrow-down-small-prelight.png  \
	dark/gtk-2.0/assets/arrow-down-small.png  \
	dark/gtk-2.0/assets/arrow-down.png  \
	dark/gtk-2.0/assets/arrow-left-insens.png  \
	dark/gtk-2.0/assets/arrow-left-prelight.png  \
	dark/gtk-2.0/assets/arrow-left.png  \
	dark/gtk-2.0/assets/arrow-right-insens.png  \
	dark/gtk-2.0/assets/arrow-right-prelight.png  \
	dark/gtk-2.0/assets/arrow-right.png  \
	dark/gtk-2.0/assets/arrow-up-insens.png  \
	dark/gtk-2.0/assets/arrow-up-prelight.png  \
	dark/gtk-2.0/assets/arrow-up-small-insens.png  \
	dark/gtk-2.0/assets/arrow-up-small-prelight.png  \
	dark/gtk-2.0/assets/arrow-up-small.png  \
	dark/gtk-2.0/assets/arrow-up.png  \
	dark/gtk-2.0/assets/button-active.png  \
	dark/gtk-2.0/assets/button-hover.png  \
	dark/gtk-2.0/assets/button-insensitive.png  \
	dark/gtk-2.0/assets/button.png  \
	dark/gtk-2.0/assets/checkbox-checked-insensitive.png  \
	dark/gtk-2.0/assets/checkbox-checked.png  \
	dark/gtk-2.0/assets/checkbox-unchecked-insensitive.png  \
	dark/gtk-2.0/assets/checkbox-unchecked.png  \
	dark/gtk-2.0/assets/combo-entry-button-active-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-button-active.png  \
	dark/gtk-2.0/assets/combo-entry-button-insensitive-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-button-insensitive.png  \
	dark/gtk-2.0/assets/combo-entry-button-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-button.png  \
	dark/gtk-2.0/assets/combo-entry-focus-notebook-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-focus-notebook.png  \
	dark/gtk-2.0/assets/combo-entry-focus-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-focus.png  \
	dark/gtk-2.0/assets/combo-entry-insensitive-notebook-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-insensitive-notebook.png  \
	dark/gtk-2.0/assets/combo-entry-insensitive-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-insensitive.png  \
	dark/gtk-2.0/assets/combo-entry-notebook-rtl.png  \
	dark/gtk-2.0/assets/combo-entry-notebook.png  \
	dark/gtk-2.0/assets/combo-entry-rtl.png  \
	dark/gtk-2.0/assets/combo-entry.png  \
	dark/gtk-2.0/assets/down-background-disable-rtl.png  \
	dark/gtk-2.0/assets/down-background-disable.png  \
	dark/gtk-2.0/assets/down-background-rtl.png  \
	dark/gtk-2.0/assets/down-background.png  \
	dark/gtk-2.0/assets/entry-border-active-bg-solid.png  \
	dark/gtk-2.0/assets/entry-border-active-bg.png  \
	dark/gtk-2.0/assets/entry-border-bg-solid.png  \
	dark/gtk-2.0/assets/entry-border-bg.png  \
	dark/gtk-2.0/assets/entry-border-disabled-bg.png  \
	dark/gtk-2.0/assets/entry-border-fill.png  \
	dark/gtk-2.0/assets/focus-line.png  \
	dark/gtk-2.0/assets/frame-gap-end.png  \
	dark/gtk-2.0/assets/frame-gap-start.png  \
	dark/gtk-2.0/assets/frame.png  \
	dark/gtk-2.0/assets/handle-h.png  \
	dark/gtk-2.0/assets/handle-v.png  \
	dark/gtk-2.0/assets/inline-toolbar.png  \
	dark/gtk-2.0/assets/line-h.png  \
	dark/gtk-2.0/assets/line-v.png  \
	dark/gtk-2.0/assets/menu-arrow-prelight.png  \
	dark/gtk-2.0/assets/menu-arrow.png  \
	dark/gtk-2.0/assets/menu-checkbox-checked-insensitive.png  \
	dark/gtk-2.0/assets/menu-checkbox-checked.png  \
	dark/gtk-2.0/assets/menu-checkbox-unchecked-insensitive.png  \
	dark/gtk-2.0/assets/menu-checkbox-unchecked.png  \
	dark/gtk-2.0/assets/menu-radio-checked-insensitive.png  \
	dark/gtk-2.0/assets/menu-radio-checked.png  \
	dark/gtk-2.0/assets/menu-radio-unchecked-insensitive.png  \
	dark/gtk-2.0/assets/menu-radio-unchecked.png  \
	dark/gtk-2.0/assets/menubar.png  \
	dark/gtk-2.0/assets/menubar_button.png  \
	dark/gtk-2.0/assets/menuitem.png  \
	dark/gtk-2.0/assets/minus.png  \
	dark/gtk-2.0/assets/notebook-entry-border-active-bg.png  \
	dark/gtk-2.0/assets/notebook-entry-border-bg.png  \
	dark/gtk-2.0/assets/notebook-entry-border-disabled-bg.png  \
	dark/gtk-2.0/assets/notebook-gap-horiz.png  \
	dark/gtk-2.0/assets/notebook-gap-vert.png  \
	dark/gtk-2.0/assets/notebook.png  \
	dark/gtk-2.0/assets/null.png  \
	dark/gtk-2.0/assets/plus.png  \
	dark/gtk-2.0/assets/progressbar.png  \
	dark/gtk-2.0/assets/progressbar_v.png  \
	dark/gtk-2.0/assets/radio-checked-insensitive.png  \
	dark/gtk-2.0/assets/radio-checked.png  \
	dark/gtk-2.0/assets/radio-unchecked-insensitive.png  \
	dark/gtk-2.0/assets/radio-unchecked.png  \
	dark/gtk-2.0/assets/slider-horiz-active.png  \
	dark/gtk-2.0/assets/slider-horiz-insens.png  \
	dark/gtk-2.0/assets/slider-horiz-prelight.png  \
	dark/gtk-2.0/assets/slider-horiz.png  \
	dark/gtk-2.0/assets/slider-insensitive.png  \
	dark/gtk-2.0/assets/slider-prelight.png  \
	dark/gtk-2.0/assets/slider-vert-active.png  \
	dark/gtk-2.0/assets/slider-vert-insens.png  \
	dark/gtk-2.0/assets/slider-vert-prelight.png  \
	dark/gtk-2.0/assets/slider-vert.png  \
	dark/gtk-2.0/assets/slider.png  \
	dark/gtk-2.0/assets/tab-bottom-active.png  \
	dark/gtk-2.0/assets/tab-left-active.png  \
	dark/gtk-2.0/assets/tab-right-active.png  \
	dark/gtk-2.0/assets/tab-top-active.png  \
	dark/gtk-2.0/assets/toolbar-entry-border-active-bg.png  \
	dark/gtk-2.0/assets/toolbar-entry-border-bg.png  \
	dark/gtk-2.0/assets/toolbar-entry-border-disabled-bg.png  \
	dark/gtk-2.0/assets/toolbar.png  \
	dark/gtk-2.0/assets/tree_header.png  \
	dark/gtk-2.0/assets/trough-horizontal-active.png  \
	dark/gtk-2.0/assets/trough-horizontal.png  \
	dark/gtk-2.0/assets/trough-progressbar.png  \
	dark/gtk-2.0/assets/trough-progressbar_v.png  \
	dark/gtk-2.0/assets/trough-scrollbar-horiz.png  \
	dark/gtk-2.0/assets/trough-scrollbar-vert.png  \
	dark/gtk-2.0/assets/trough-vertical-active.png  \
	dark/gtk-2.0/assets/trough-vertical.png  \
	dark/gtk-2.0/assets/up-background-disable-rtl.png  \
	dark/gtk-2.0/assets/up-background-disable.png  \
	dark/gtk-2.0/assets/up-background-rtl.png  \
	dark/gtk-2.0/assets/up-background.png  \
	dark/gtk-2.0/menubar-toolbar/button-active.png  \
	dark/gtk-2.0/menubar-toolbar/button-hover.png  \
	dark/gtk-2.0/menubar-toolbar/button-insensitive.png  \
	dark/gtk-2.0/menubar-toolbar/button.png  \
	dark/gtk-2.0/menubar-toolbar/menubar-dark.png  \
	dark/gtk-2.0/menubar-toolbar/menubar-toolbar-dark.rc  \
	dark/gtk-2.0/menubar-toolbar/menubar-toolbar.rc  \
	dark/gtk-2.0/menubar-toolbar/menubar.png  \
	dark/gtk-2.0/menubar-toolbar/menubar_button-dark.png  \
	dark/gtk-2.0/menubar-toolbar/menubar_button.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-active-bg-dark.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-active-bg.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-bg-dark.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-bg.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-disabled-bg-dark.png  \
	dark/gtk-2.0/menubar-toolbar/toolbar-entry-border-disabled-bg.png  \
	dark/gtk-2.0/apps.rc  \
	dark/gtk-2.0/gtkrc  \
	dark/gtk-2.0/main.rc  \
	dark/gtk-2.0/panel.rc

#  I should put Makefiles in all intermediate directories, let's get lazy
build-recursive clean-recursive install-recursive:
	-@:

build clean:
	-@:

install:
	for file in $(files); \
	do \
	  mkdir -p `dirname $(DESTDIR)/$(dir)/$$file`; \
	  cp $$file $(DESTDIR)/$(dir)/$$file; \
	done
