#!/usr/bin/perl

$/="------------------------------------------------------------------------";

while (<>) {
	if (($m, $d)=/r\d+ \| ([^|]+) \| (\d+-\d+-\d+)/) {
		$d=~s/-\d+$//;
		
		my $alltrans=1;
		while (/ M (.*)/sg) {
			if (! /\.po/ && ! (/manual\/(\w\w)/ && $1 ne 'en')) {
				$alltrans=0;
			}
		}
		
		if (! $seen{$m}{$d}) {
			$count{$d}++;
			$seen{$m}{$d}=1;
		}
		if (! $alltrans && ! $seendev{$m}{$d}) {
			$countdev{$d}++;
			$seendev{$m}{$d}=1;
		}
	}
}

my @list=sort keys %count;
#pop @list; # remove last, probably incomplete month

foreach my $m (@list) {
	print "$m, $count{$m}, ".(defined $countdev{$m} ? $countdev{$m} : '0')."\n";
}
